var deutschland = "Deutschland 2022:";
var frankreich = "Frankreich 2022:";
var italien = "Italien 2022:";
var spanien = "Spanien 2022:";
var einwohner_de = 83.2;
var einwohner_fr = 65.8;
var einwohner_it = 60.6;
var einwohner_sp = 46.6;
var deutschland2 = "Deutschland:";
var frankreich2 = "Frankreich:";
var italien2 = "Italien:";
var spanien2 = "Spanien:";
var de_2008 = 82.2;
var fr_2008 = 62.1;
var it_2008 = 58.7;
var sp_2008 = 45.7;
var multipilkator = 100;
var gesamt_eu = 447.1;
console.log("Gesamtzahl Einwohnerinnen und Einwohner in" + " " + deutschland + einwohner_de + "Mio.");
console.log("Relativ zur Gesamtanzahl in der Eu von" + " " + deutschland + einwohner_de / gesamt_eu * multipilkator + "%");
console.log("Wachstumsrate seit 2008 in" + " " + deutschland2 + (((einwohner_de - de_2008) / de_2008) * multipilkator) + "%");
console.log("Wachstumsrate gesamt zwischen 2006 und 2022 in" + " " + deutschland2 + (einwohner_de - de_2008) + "Mio.");
console.log("Gesamtzahl Einwohnerinnen und Einwohner in" + " " + frankreich + einwohner_fr + "Mio.");
console.log("Relativ zur Gesamtanzahl in der Eu von" + " " + frankreich + einwohner_fr / gesamt_eu * multipilkator + "%");
console.log("Wachstumsrate seit 2008 in" + " " + frankreich2 + (((einwohner_fr - fr_2008) / fr_2008) * multipilkator) + "%");
console.log("Wachstumsrate gesamt zwischen 2006 und 2022 in" + " " + frankreich2 + (einwohner_fr - fr_2008) + "Mio.");
console.log("Gesamtzahl Einwohnerinnen und Einwohner in" + " " + italien + einwohner_it + "Mio.");
console.log("Relativ zur Gesamtanzahl in der Eu von" + " " + italien + einwohner_it / gesamt_eu * multipilkator + "%");
console.log("Wachstumsrate seit 2008 in" + " " + italien2 + (((einwohner_it - it_2008) / it_2008) * multipilkator) + "%");
console.log("Wachstumsrate gesamt zwischen 2006 und 2022 in" + " " + italien2 + (einwohner_it - it_2008) + "Mio.");
console.log("Gesamtzahl Einwohnerinnen und Einwohner in" + " " + spanien + einwohner_sp + "Mio.");
console.log("Relativ zur Gesamtanzahl in der Eu von" + " " + spanien + einwohner_sp / gesamt_eu * multipilkator + "%");
console.log("Wachstumsrate seit 2008 in" + " " + spanien2 + (((einwohner_sp - sp_2008) / sp_2008) * multipilkator) + "%");
console.log("Wachstumsrate gesamt zwischen 2006 und 2022 in" + " " + spanien2 + (einwohner_sp - sp_2008) + "Mio.");
//# sourceMappingURL=typescript.js.map